Feature/skiing
pcn-takefu/pcn-takefu-skills-web pull request #3
Opened 2021-08-02 09:52 UTC by thrush0329

スキーゲーム webテキスト完成

2021-08-07 06:29 UTC, morishu1108 requested changes
気になったところにコメントをいれておいたので、修正してみてください〜
自分の改造も組み込んでいてイイね！

2021-08-07 06:29 UTC, morishu1108 commented on web/skills/skiing.html
> +                                <ruby><rb>左右</rb><rt>さゆう</rt></ruby>の<ruby><rb>矢印キー</rb><rt>やじるしきー</rt></ruby>すべる<ruby><rb>方向</rb><rt>ほうこう</rt></ruby>を<ruby><rb>変</rb><rt>か</rt></ruby>えよう！
左右の矢印キーすべる方向を...
↓
左右の矢印キー**で**すべる方向を...

にしましょうか。

2021-08-07 06:29 UTC, morishu1108 commented on web/skills/skiing.html
> +                            <ruby><rb>コース</rb><rt>こーす</rt></ruby>の<ruby><rb>幅</rb><rt>はば</rt></ruby>をかえてみよう thought by Remon
考えた人のところはこんな感じにしましょう。
```
thought by Remon
```
↓
```
 <span class="author">Remon</span>
```

そして、style.cssの636行目あたりに、これを追加してもらえますかね？？
```
.l-pt-custom-item-task span.author {
  font-size: 0.9rem;
  margin-left: 4%;
  letter-spacing: 0.1rem;
}
.l-pt-custom-item-task span.author::before {
  content:"- ";
}
.l-pt-custom-item-task span.author::after {
  content:" added. -"
}
```

2021-08-07 06:29 UTC, morishu1108 commented on web/skills/skiing.html
> +                                <code class="ichigojam">270</code> や <code class="ichigojam">278</code> の <code class="ichigojam">"|"</code> と <code class="ichigojam">260</code> の <code class="ichigo
"_" があるのは、260行目じゃなくて274行目かな。

2021-08-07 06:29 UTC, morishu1108 commented on web/skills/skiing.html
> +                            <ruby><rb>速</rb><rt>はや</rt></ruby>さをだんだん<ruby><rb>速</rb><rt>はや</rt></ruby>くしてみよう thought by thrush
ここの作者の書き方も↑とどうようになおしてみてくれるかな。

2021-08-07 06:29 UTC, morishu1108 commented on web/skills/skiing.html
> +                            <code class="ichigojam">70 PRINT CHR$(5)</code> と <code class="ichigojam">140 PRINT CHR$(5)</code> の <code class="ichigojam">CHR$(5)</code> をかえてみよう！！</p>
末尾に`</p>`のとじタグがあるけど、開始の`<p>`タグがないかな。  
```
<p>
    <code class="ichigojam">70</code> と <code class="ichigojam">140</code> の <code class="ichigojam">CHR$(5)</code> をかえてみよう！！
</p>
<p>
    <code class="ichigojam">CHR$(5)</code> のかわりに <code class="ichigojam">"0"</code> のようにもかけるよ
</p>
```
という感じにしてみようか。

2021-08-07 07:39 UTC, thrush0329 commented on web/skills/skiing.html
> +                                <ruby><rb>左右</rb><rt>さゆう</rt></ruby>の<ruby><rb>矢印キー</rb><rt>やじるしきー</rt></ruby>すべる<ruby><rb>方向</rb><rt>ほうこう</rt></ruby>を<ruby><rb>変</rb><rt>か</rt></ruby>えよう！
了解です

2021-08-07 07:44 UTC, thrush0329 commented on web/skills/skiing.html
> +                            <ruby><rb>コース</rb><rt>こーす</rt></ruby>の<ruby><rb>幅</rb><rt>はば</rt></ruby>をかえてみよう thought by Remon
わかりました

2021-08-07 07:45 UTC, thrush0329 commented on web/skills/skiing.html
> +                                <code class="ichigojam">270</code> や <code class="ichigojam">278</code> の <code class="ichigojam">"|"</code> と <code class="ichigojam">260</code> の <code class="ichigo
了解です

2021-08-07 08:00 UTC, thrush0329 commented on web/skills/skiing.html
> +                            <ruby><rb>速</rb><rt>はや</rt></ruby>さをだんだん<ruby><rb>速</rb><rt>はや</rt></ruby>くしてみよう thought by thrush
わかりました

2021-08-07 08:00 UTC, thrush0329 commented on web/skills/skiing.html
> +                            <code class="ichigojam">70 PRINT CHR$(5)</code> と <code class="ichigojam">140 PRINT CHR$(5)</code> の <code class="ichigojam">CHR$(5)</code> をかえてみよう！！</p>
わかりました

2021-08-07 08:05 UTC, thrush0329 commented
レビューの指摘事項を改善

2021-08-08 14:18 UTC, morishu1108 commented on web/skills/skiing.html
> +                                <ruby><rb>左右</rb><rt>さゆう</rt></ruby>の<ruby><rb>矢印キー</rb><rt>やじるしきー</rt></ruby>すべる<ruby><rb>方向</rb><rt>ほうこう</rt></ruby>を<ruby><rb>変</rb><rt>か</rt></ruby>えよう！
修正確認しましたー！OKです〜

2021-08-08 14:18 UTC, morishu1108 commented on web/skills/skiing.html
> +                            <ruby><rb>コース</rb><rt>こーす</rt></ruby>の<ruby><rb>幅</rb><rt>はば</rt></ruby>をかえてみよう thought by Remon
修正確認しましたー！OKです〜

2021-08-08 14:18 UTC, morishu1108 commented on web/skills/skiing.html
> +                            <code class="ichigojam">70 PRINT CHR$(5)</code> と <code class="ichigojam">140 PRINT CHR$(5)</code> の <code class="ichigojam">CHR$(5)</code> をかえてみよう！！</p>
修正確認しましたー！OKです〜

2021-08-08 14:18 UTC, morishu1108 commented on web/skills/skiing.html
> +                            <ruby><rb>速</rb><rt>はや</rt></ruby>さをだんだん<ruby><rb>速</rb><rt>はや</rt></ruby>くしてみよう thought by thrush
修正確認しましたー！OKです〜

2021-08-08 14:18 UTC, morishu1108 commented on web/skills/skiing.html
> +                                <code class="ichigojam">270</code> や <code class="ichigojam">278</code> の <code class="ichigojam">"|"</code> と <code class="ichigojam">260</code> の <code class="ichigo
修正確認しましたー！OKです〜

2021-08-08 14:19 UTC, merged