Feature/hayauchi-remodeling
pcn-takefu/pcn-takefu-skills-web pull request #4
Opened 2021-08-06 09:25 UTC by thrush0329

はやうち名人(改造版) 追加

2021-08-07 06:56 UTC, morishu1108 requested changes
コメントしておいたので、確認&修正よろしく！

2021-08-07 06:56 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +                            すうじ<ruby><rb>名人</rb><rt>めいじん</rt></ruby>にしてみよう　thought by た
考えた人のところはこんな感じにしましょう。
```
thought by た
```
↓
```html
 <span class="author">た</span>
```

そして、style.cssの636行目あたりに、これを追加してもらえますかね？？（もう入っていればいれなくてOK）
```css
.l-pt-custom-item-task span.author {
  font-size: 0.9rem;
  margin-left: 4%;
  letter-spacing: 0.1rem;
}
.l-pt-custom-item-task span.author::before {
  content:"- ";
}
.l-pt-custom-item-task span.author::after {
  content:" added. -"
}
```

2021-08-07 06:56 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +                            <ruby><rb>正</rb><rt>ただ</rt></ruby>しくいれたら<ruby><rb>BEEP</rb><rt>びーぷ</rt></ruby>しよう
BEEPときいてピンとこない人もいると思うので、
```
BEEPしよう
```
↓
```
正解の音をならそう
```
とかでどうかな？

2021-08-07 06:56 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +                            まちがえたら<ruby><rb>前</rb><rt>まえ</rt></ruby>とちがう<ruby><rb>音</rb><rt>おと</rt></ruby>で<ruby><rb>BEEP</rb><rt>びーぷ</rt></ruby>しよう
`前とちがう音...` の **"前"** が何をさしているかわかりにくいので、`正解の音とはちがう音...`という表現にしてみてはどうかな？

2021-08-07 06:56 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +                                <code class="ichigojam">20</code>　の <code class="ichigojam">65</code> を <code class="ichigojam">48</code>にしてみよう<br>
数字がいくつも並んでいると、行番号かコードのなかの数字かわかりにくいかもと思ったので、
```html
<code class="ichigojam">20</code>　の <code class="ichigojam">N=65</code> を <code class="ichigojam">N=48</code>にしてみよう<br>
<code class="ichigojam">60</code>　の <code class="ichigojam">N&lt;>91</code> を <code class="ichigojam">N&lt;>58</code>にしてみよう
```
としてはどうだろか？？

2021-08-07 06:56 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +                                <label for="50">50 IF INKEY()&lt;>N GOTO 30</label>
ちゃんと特殊文字の書き方をマスターしてますな！素晴らしい！！

2021-08-07 06:56 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +                                <p>上記URLをもとにPCN武生で改造
`<p>` タグの閉じタグがなさそうね。

2021-08-07 06:56 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +    <meta property="og:url" content="https://pcntakefu.club/skills/hayauzhi-meizin-remodeling.html">
ここのURLのファイル名が実際のファイル名とちがっているみたいね。ご確認を。

2021-08-07 08:14 UTC, thrush0329 commented on web/skills/hayauchi-remodeling.html
> +                            すうじ<ruby><rb>名人</rb><rt>めいじん</rt></ruby>にしてみよう　thought by た
わかりました

2021-08-07 08:18 UTC, thrush0329 commented on web/skills/hayauchi-remodeling.html
> +                            <ruby><rb>正</rb><rt>ただ</rt></ruby>しくいれたら<ruby><rb>BEEP</rb><rt>びーぷ</rt></ruby>しよう
了解です

2021-08-07 08:21 UTC, thrush0329 commented on web/skills/hayauchi-remodeling.html
> +                            まちがえたら<ruby><rb>前</rb><rt>まえ</rt></ruby>とちがう<ruby><rb>音</rb><rt>おと</rt></ruby>で<ruby><rb>BEEP</rb><rt>びーぷ</rt></ruby>しよう
わかりました

2021-08-07 08:22 UTC, thrush0329 commented on web/skills/hayauchi-remodeling.html
> +                                <code class="ichigojam">20</code>　の <code class="ichigojam">65</code> を <code class="ichigojam">48</code>にしてみよう<br>
了解です

2021-08-07 08:23 UTC, thrush0329 commented on web/skills/hayauchi-remodeling.html
> +                                <label for="50">50 IF INKEY()&lt;>N GOTO 30</label>
ありがとうございます！

2021-08-07 08:23 UTC, thrush0329 commented on web/skills/hayauchi-remodeling.html
> +                                <p>上記URLをもとにPCN武生で改造
わかりました

2021-08-07 08:24 UTC, thrush0329 commented on web/skills/hayauchi-remodeling.html
> +    <meta property="og:url" content="https://pcntakefu.club/skills/hayauzhi-meizin-remodeling.html">
わかりました

2021-08-07 08:27 UTC, thrush0329 commented
レビューの指摘事項を改善しました

2021-08-08 14:22 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +                            すうじ<ruby><rb>名人</rb><rt>めいじん</rt></ruby>にしてみよう　thought by た
修正確認しましたー！OKです〜

2021-08-08 14:23 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +                            まちがえたら<ruby><rb>前</rb><rt>まえ</rt></ruby>とちがう<ruby><rb>音</rb><rt>おと</rt></ruby>で<ruby><rb>BEEP</rb><rt>びーぷ</rt></ruby>しよう
修正確認しましたー！OKです〜

2021-08-08 14:23 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +                                <code class="ichigojam">20</code>　の <code class="ichigojam">65</code> を <code class="ichigojam">48</code>にしてみよう<br>
修正確認しましたー！OKです〜

2021-08-08 14:24 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +                                <p>上記URLをもとにPCN武生で改造
修正確認しましたー！OKです〜

2021-08-08 14:26 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +    <meta property="og:url" content="https://pcntakefu.club/skills/hayauzhi-remodeling.html">
まだスペルがちがうみたいね。基本ファイル名とかは実際のファイル名をコピーして貼り付けるくせをつけましょう。
（タイプミスでバグになるのはもったいないので。）

2021-08-08 14:26 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +                            <ruby><rb>正</rb><rt>ただ</rt></ruby>しくいれたら<ruby><rb>BEEP</rb><rt>びーぷ</rt></ruby>しよう
修正確認しましたー！OKです〜

2021-08-08 14:27 UTC, morishu1108 commented on web/skills/hayauchi-remodeling.html
> +    <meta property="og:url" content="https://pcntakefu.club/skills/hayauzhi-meizin-remodeling.html">
ここ最新でもなおってなかったので（まだ1文字スペルミスあり）確認よろしく！！

2021-08-08 14:27 UTC, morishu1108 requested changes
1点指摘がまだあるのでご確認ください〜！

2021-08-09 07:37 UTC, thrush0329 commented on web/skills/hayauchi-remodeling.html
> +    <meta property="og:url" content="https://pcntakefu.club/skills/hayauzhi-remodeling.html">
わかりました

2021-08-09 07:38 UTC, thrush0329 commented
レビューの指摘事項を改善しました

2021-08-10 23:44 UTC, merged