Feature/invader-game
pcn-takefu/pcn-takefu-skills-web pull request #7
Opened 2021-09-23 12:08 UTC by thrush0329

インベーダーゲームwebプリント完成

2021-10-07 08:37 UTC, morishu1108 requested changes
レビューしてコメントしておきました！
LRUNつかう形にしちゃってもよいかもとちょっと思った。プログラム自体を。
また意見きかせてくださいな〜。

2021-10-07 08:37 UTC, morishu1108 commented on web/skills/invader-game.html
> +                                <label for="1">キャラクターコード</label>
上でコードの枠外で"キャラクターコード"とタイトルつけているので、ここはなくてもいい気がする。
ちょっとしたことだけど、むだに行がふえると、その分使う人がスクロールしないといけないところがふえるのでね。

2021-10-07 08:37 UTC, morishu1108 commented on web/skills/invader-game.html
> +                                <ruby><rb>キャラクターコード</rb><rt>きゃらくたーこーど</rt></ruby>の <code class="ichigojam">110</code> や <code class="ichigojam">120</code><ruby> などを<rb>変更</rb><rt>へんこう</rt></ruby>してみよ
ここルビが少しずれているので調整よろしく！

2021-10-07 12:29 UTC, thrush0329 commented on web/skills/invader-game.html
> +                                <label for="1">キャラクターコード</label>
了解です。

2021-10-07 12:29 UTC, thrush0329 commented on web/skills/invader-game.html
> +                                <ruby><rb>キャラクターコード</rb><rt>きゃらくたーこーど</rt></ruby>の <code class="ichigojam">110</code> や <code class="ichigojam">120</code><ruby> などを<rb>変更</rb><rt>へんこう</rt></ruby>してみよ
了解です

2021-10-07 12:30 UTC, thrush0329 commented
レビューの指摘事項を修正

2021-10-30 14:51 UTC, morishu1108 commented on web/skills/invader-game.html
> +                                <label for="1">キャラクターコード</label>
修正確認しました〜！

2021-10-30 14:53 UTC, morishu1108 commented on web/skills/invader-game.html
> +                                <ruby><rb>キャラクターコード</rb><rt>きゃらくたーこーど</rt></ruby>の <code class="ichigojam">110</code> や <code class="ichigojam">120</code><ruby> などを<rb>変更</rb><rt>へんこう</rt></ruby>してみよ
修正確認しました〜！

2021-10-30 14:56 UTC, merged